### ISSUE TITLE
Include in tm-forge?

### ISSUE THREAD

**Issue by mgubi** [XmacsLabs/quiver#2]
@darcy-shen ideally tm-forge is the place designed to collect all these small plugin, so the users know where to look for something. Would you mind if I add it here and we move the development there?

**Comment by da-liii** [comment]
It should be migrated to https://github.com/texmacs/plugins-in-python.

Since Mogan v1.1.3, I will create the plugin center. And Python implemented plugins will be packaged in PEX for macOS and Linux, in exe for Windows.

**Comment by da-liii** [comment]
I just talked about Pants and PEX (using the GNU TeXmacs sympy plugin as a demo) in the 10m lightning talk for PyCon China 2022.

https://www.bilibili.com/video/BV1L3411S76J/
